name: Validate filenames

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Filenames
        uses: kurnev/match-against-glob-action@v1
        with:
          filenames: './**/*.*'
          patterns: '^((?![\\\/:*?\"<>|]).)*$'
