name: Validate filenames

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Filenames
        uses: scheduleonce/filenames-linter@v2.0.0
        with:
          path: './**/*'
          pattern: '^((?![\\\/:*?\"<>|]).)*$'
