name: Validate filenames

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Filenames
        uses: csunibo/filenames-linter@v1.4.1
        with:
          path: './'
          pattern: '^((?![\\\/:*?\"<>|]).)*$'
          recursive: true
